from qutip import Qobj


def static_propagator(
    hamiltonian: Qobj,
    time: float,
) -> Qobj:
    """Return the propagator generated by a time-independent Hamiltonian."""
    return (-1j * hamiltonian * time).expm()


def rotating_frame_propagator(
    propagator: Qobj,
    generator: Qobj,
    time: float,
) -> Qobj:
    """Transform a propagator into a rotating frame."""
    frame = (-1j * generator * time).expm()

    return frame.dag() * propagator

