from qutip import Qobj, qeye

from echo_spin.dynamics.propagators import time_dependent_propagator

def toggling_hamiltonians(
    free_hamiltonian: Qobj,
    pulses: list[Qobj],
) -> list[Qobj]:
    """Return the toggling-frame Hamiltonian for each free interval."""
    cumulative = qeye(free_hamiltonian.dims[0])

    hamiltonians = [free_hamiltonian]

    for pulse in pulses:
        cumulative = pulse * cumulative
        hamiltonians.append(
            cumulative * free_hamiltonian * cumulative.dag()
        )

    return hamiltonians


def toggling_propagator(
    hamiltonians: list[Qobj],
    durations: list[float],
) -> Qobj:
    """Return the propagator generated by consecutive toggling-frame intervals."""
    if len(hamiltonians) != len(durations):
        raise ValueError(
            "hamiltonians and durations must have the same length."
        )

    if not hamiltonians:
        raise ValueError("At least one interval is required.")

    propagator = qeye(hamiltonians[0].dims[0])

    for hamiltonian, duration in zip(hamiltonians, durations):
        interval = (-1j * hamiltonian * duration).expm()
        propagator = interval * propagator

    return propagator


def finite_pulse_propagator(
    free_hamiltonian: Qobj,
    control_operator: Qobj,
    duration: float,
    envelope,
    steps: int,
    start_time: float = 0.0,
) -> Qobj:
    """Propagate a finite control pulse while the free Hamiltonian remains active."""

    def hamiltonian(time):
        return (
            free_hamiltonian
            + envelope(time) * control_operator
        )

    return time_dependent_propagator(
        hamiltonian=hamiltonian,
        t0=start_time,
        t1=start_time + duration,
        steps=steps,
    )


def finite_pulse_sequence_propagator(
    free_hamiltonian: Qobj,
    durations: list[float],
    pulse_propagators: list[Qobj],
) -> Qobj:
    """Propagate alternating free-evolution intervals and finite pulses."""
    if len(durations) != len(pulse_propagators) + 1:
        raise ValueError(
            "There must be one more free interval than pulse propagators."
        )

    propagator = qeye(free_hamiltonian.dims[0])

    for index, duration in enumerate(durations):
        free_interval = (
            -1j * free_hamiltonian * duration
        ).expm()

        propagator = free_interval * propagator

        if index < len(pulse_propagators):
            propagator = pulse_propagators[index] * propagator

    return propagator