from qutip import Qobj, qeye


def toggling_hamiltonians(
    free_hamiltonian: Qobj,
    pulses: list[Qobj],
) -> list[Qobj]:
    """Return the toggling-frame Hamiltonian for each free interval."""
    cumulative = qeye(free_hamiltonian.dims[0])

    hamiltonians = [free_hamiltonian]

    for pulse in pulses:
        cumulative = pulse * cumulative
        hamiltonians.append(
            cumulative * free_hamiltonian * cumulative.dag()
        )

    return hamiltonians


def toggling_propagator(
    hamiltonians: list[Qobj],
    durations: list[float],
) -> Qobj:
    """Return the propagator generated by consecutive toggling-frame intervals."""
    if len(hamiltonians) != len(durations):
        raise ValueError(
            "hamiltonians and durations must have the same length."
        )

    if not hamiltonians:
        raise ValueError("At least one interval is required.")

    propagator = qeye(hamiltonians[0].dims[0])

    for hamiltonian, duration in zip(hamiltonians, durations):
        interval = (-1j * hamiltonian * duration).expm()
        propagator = interval * propagator

    return propagator