import numpy as np
import pytest
from qutip import Qobj, sigmax, sigmay, sigmaz, qeye

from echo_spin.dynamics.sequences import (
    toggling_hamiltonians,
    toggling_propagator,
)


def test_toggling_hamiltonians():
    """Check Hamiltonians generated by cumulative pulse transformations."""
    hamiltonian = Qobj([
        [1.0, 0.0],
        [0.0, -1.0],
    ])

    pulse = -1j * sigmax()

    toggled = toggling_hamiltonians(
        free_hamiltonian=hamiltonian,
        pulses=[pulse],
    )

    expected = pulse * hamiltonian * pulse.dag()

    assert len(toggled) == 2
    assert np.allclose(toggled[0].full(), hamiltonian.full())
    assert np.allclose(toggled[1].full(), expected.full())


def test_toggling_propagator_single_interval():
    """Check propagation during one free-evolution interval."""
    hamiltonian = Qobj([
        [1.0, 0.0],
        [0.0, -1.0],
    ])

    propagator = toggling_propagator(
        hamiltonians=[hamiltonian],
        durations=[0.5],
    )

    expected = (-1j * hamiltonian * 0.5).expm()

    assert np.allclose(propagator.full(), expected.full())


def test_toggling_propagator_rejects_mismatched_lengths():
    """Check that every interval has a corresponding duration."""
    hamiltonian = Qobj([
        [1.0, 0.0],
        [0.0, -1.0],
    ])

    with pytest.raises(ValueError):
        toggling_propagator(
            hamiltonians=[hamiltonian],
            durations=[0.2, 0.3],
        )


def test_pi_pulse_refocuses_static_detuning():
    """Check ideal refocusing of a static single-qubit detuning."""
    hamiltonian = sigmaz()
    pi_x = -1j * sigmax()

    toggled = toggling_hamiltonians(
        free_hamiltonian=hamiltonian,
        pulses=[pi_x],
    )

    propagator = toggling_propagator(
        hamiltonians=toggled,
        durations=[0.5, 0.5],
    )

    assert np.allclose(
        propagator.full(),
        qeye(2).full(),
    )